module-template: ! 'module MODULE_NAME where

'
extensions: {}
environment: ghc-7.4.2-stable-13.09
cabal-file: project.cabal
hidden-packages: ''
version: 1
extra-packages: ''
ghc-args: []
excluded-modules:
- http-client-conduit/Setup.hs
- http-client-multipart/Setup.hs
- http-client-openssl/Network/HTTP/Client/OpenSSL.hs
- http-client-openssl/Setup.hs
- http-client-openssl/test/Spec.hs
- http-client-tls/Setup.hs
- http-client-tls/test/Spec.hs
- http-client/Network/HTTP/Client/Core.hs
- http-client/Network/HTTP/Client/Internal.hs
- http-client/Setup.hs
- http-client/test/Spec.hs
- http-conduit/Network/HTTP/Conduit.hs
- http-conduit/http.hs
- http-conduit/test-server.hs
- http-conduit/test.hs
- http-conduit/test/CookieTest.hs
- http-conduit/test/main.hs
